---
apiVersion: batch/v1
kind: Job
metadata:
  name: base
  labels:
    app: base
spec:
  template:
    metadata:
      name: base
      labels:
        app: base
    spec:
      restartPolicy: Never
      volumes:
        - name: mytest
          hostPath:
            path: /Users/zhoupeng/Documents/mytest
      containers:
        - name: scaler
          image: registry.cn-hangzhou.aliyuncs.com/beeper/scaler:v6.3
          command: [ "./run.sh" ]
        - name: serverless-simulator
          image: registry.cn-beijing.aliyuncs.com/cloudnative-challenge/simulator:v1.3.3
          command: [ "./run.sh" ]
          args: [ "8b83S" ]
          volumeMounts:
            - name: mytest
              mountPath: /tmp/data
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sim
  labels:
    app: sim
spec:
  template:
    metadata:
      name: sim
      labels:
        app: sim
    spec:
      restartPolicy: Never
      volumes:
        - name: mytest
          hostPath:
            path: /Users/zhoupeng/Documents/mytest
      containers:
        - name: scaler
          image: registry.cn-hangzhou.aliyuncs.com/beeper/scaler:v6.8
          command: [ "./run.sh" ]
        - name: serverless-simulator
          image: registry.cn-beijing.aliyuncs.com/cloudnative-challenge/simulator:v1.3.3
          command: [ "./run.sh" ]
          args: [ "8b83S" ]
          volumeMounts:
            - name: mytest
              mountPath: /tmp/data
