---
apiVersion: batch/v1
kind: Job
metadata:
  name: sim1
  labels:
    app: sim1
spec:
  template:
    metadata:
      name: sim1
      labels:
        app: sim1
    spec:
      restartPolicy: Never
      volumes:
        - name: mytest
          hostPath:
            path: /Users/zhoupeng/Documents/mytest
      containers:
        - name: scaler
          image: registry.cn-hangzhou.aliyuncs.com/beeper/scaler:v913
          command: [ "./run.sh" ]
          env:
            - name: "dev"
              value: "true"
        - name: serverless-simulator
          image: registry.cn-beijing.aliyuncs.com/cloudnative-challenge/simulator:v1.3.5
          command: [ "./run.sh" ]
          args: [ "0307" ]
          volumeMounts:
            - name: mytest
              mountPath: /tmp/data
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sim2
  labels:
    app: sim2
spec:
  template:
    metadata:
      name: sim2
      labels:
        app: sim2
    spec:
      restartPolicy: Never
      volumes:
        - name: mytest
          hostPath:
            path: /Users/zhoupeng/Documents/mytest
      containers:
        - name: scaler
          image: registry.cn-hangzhou.aliyuncs.com/beeper/scaler:v913
          command: [ "./run.sh" ]
          env:
            - name: "dev"
              value: "true"
        - name: serverless-simulator
          image: registry.cn-beijing.aliyuncs.com/cloudnative-challenge/simulator:v1.3.5
          command: [ "./run.sh" ]
          args: [ "8b83S" ]
          volumeMounts:
            - name: mytest
              mountPath: /tmp/data
#---
#apiVersion: batch/v1
#kind: Job
#metadata:
#  name: 
#  labels:
#    app: 
#spec:
#  template:
#    metadata:
#      name: 
#      labels:
#        app: 
#    spec:
#      restartPolicy: Never
#      volumes:
#        - name: mytest
#          hostPath:
#            path: /Users/zhoupeng/Documents/mytest
#      containers:
#        - name: scaler
#          image: registry.cn-hangzhou.aliyuncs.com/beeper/scaler:v913
#          command: [ "./run.sh" ]
#          env:
#            - name: "dev"
#              value: "true"
#        - name: serverless-simulator
#          image: registry.cn-beijing.aliyuncs.com/cloudnative-challenge/simulator:v1.3.5
#          command: [ "./run.sh" ]
#          args: [ "" ]
#          volumeMounts:
#            - name: mytest
#              mountPath: /tmp/data