---
apiVersion: batch/v1
kind: Job
metadata:
  name: sim3
  labels:
    app: sim3
spec:
  template:
    metadata:
      name: sim3
      labels:
        app: sim3
    spec:
      restartPolicy: Never
      volumes:
        - name: mytest
          hostPath:
            path: /Users/zhoupeng/Documents/mytest
      containers:
        - name: scaler
          image: registry.cn-hangzhou.aliyuncs.com/beeper/scaler:v882
          command: [ "./run.sh" ]
          env:
            - name: "dev"
              value: "true"
        - name: serverless-simulator
          image: registry.cn-beijing.aliyuncs.com/cloudnative-challenge/simulator:v1.3.5
          command: [ "./run.sh" ]
          args: [ "dataSet_3" ]
          volumeMounts:
            - name: mytest
              mountPath: /tmp/data